sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

language: python

python:
  - "2.7"

env:
  global:
    - VERSION="10.0" TESTS="0" LINT_CHECK="0"
    - TRANSIFEX_USER='transbot@odoo-community.org'
    - secure: Q3NYtZSe8DFS4/0JL8ki9NdIvP0NFY/ZRWtAQCDdcDdHKeSEjkCtf5btFuF0if1wa62UI4ZrDqT1/Fix2zAT5PW7mjAio0h2DYJAxBIZa7VIZEJC4tB93xgHq9SFByNGG5iE/zwXwTPLGpiGSnLgNgw0Zndv3ZTAJNhaxpKtqIo=
  matrix:
    - LINT_CHECK="1"
    - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE=stock_auto_move
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE=stock_auto_move
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE=stock_auto_move
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE=stock_auto_move


virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
