sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

language: python

python:
  - "2.7"

env:
  global:
    - VERSION="10.0" TESTS="0" LINT_CHECK="0"
  matrix:
    - LINT_CHECK="1"
    - TESTS="1" ODOO_REPO="odoo/odoo"
    - TESTS="1" ODOO_REPO="OCA/OCB"
#    - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="picking_dispatch,stock_split_picking"
#    - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="picking_dispatch,stock_split_picking"
#    - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="picking_dispatch"
#    - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="picking_dispatch"
#    - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="stock_split_picking"
#    - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="stock_split_picking"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
