language: python

python:
  - "2.7"

env:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" INCLUDE="stock_route_transit, stock_shipment_management" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" INCLUDE="stock_route_transit, stock_shipment_management" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" EXCLUDE="stock_route_transit, stock_shipment_management" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" EXCLUDE="stock_route_transit, stock_shipment_management" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly
  - pip install coveralls flake8
  - git clone https://github.com/OCA/product-attribute -b ${VERSION} $HOME/product-attribute
  - git clone https://github.com/OCA/webkit-tools -b ${VERSION} $HOME/webkit-tools
  - git clone https://github.com/OCA/stock-logistics-warehouse -b ${VERSION} $HOME/stock-logistics-warehouse

script:
  - travis_run_tests

after_success:
  coveralls
